//! https://github.com/Prakhar-002/LEETCODE

// Todo 💎 QUESTION NUMBER Quest Maths L7 Q1

//? ⌚ Time complexity ➺ O(n) 👉🏻  n = len(nums)

//? 🧺 Space complexity ➺ O(1)

import java.util.*;

class Solution {
      public List<Integer> grayCode(int n) {
            List<Integer> result = new ArrayList<>();
            int totalNumbers = 1 << n;   // Compute 2^n numbers for n-bit Gray code

            // Generate all Gray code numbers from 0 to 2^n - 1
            for (int i = 0; i < totalNumbers; i++) {
                  // Each Gray code is generated by XORing i with i shifted right by 1
                  result.add(i ^ (i >> 1));
            }

            return result;  // Return the list of n-bit Gray codes
      }
}
